databases:
  - name: RubyOnRailsVentas

services:
  - type: web
    name: RubyOnRailsVentas
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: RubyOnRailsVentas
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false