databases:
  - name: postgres
    ipAllowList: []
    database: RubyOnRailsVentas_development
    user: rails

services:
  - type: web
    name: RubyOnRailsVentas
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false